<?php

namespace LocalMediaProxy\Features;

/**
 * Class Proxy
 *
 * Handles rewriting attachment URLs to the remote CDN when local files are missing.
 */
class Proxy
{
    /**
     * Registers the filters that rewrite missing local media URLs.
     */
    public function register(): void
    {
        add_filter('wp_get_attachment_url', [$this, 'rewrite_missing_media_url'], 10, 2);
        add_filter('wp_get_attachment_image_src', [$this, 'rewrite_image_src'], 10, 4);
        add_filter('wp_calculate_image_srcset', [$this, 'rewrite_srcset'], 10, 5);
        add_filter('wp_get_attachment_image_url', [$this, 'rewrite_image_url'], 10, 2);

        // Enable rewriting <img src="..."> in post content with raw HTML images.
        add_filter('the_content', [$this, 'rewrite_images_in_content'], 20);
    }

    /**
     * Rewrites the attachment URL to the remote proxy API if the local file is missing.
     *
     * @param string $url The original URL generated by WordPress.
     * @param int $post_id The attachment post ID.
     * @return string The final URL (either original or rewritten to remote proxy).
     */
    public function rewrite_missing_media_url(string $url, int $post_id = 0): string
    {
        $uploads = wp_get_upload_dir();
        if (empty($uploads['baseurl']) || empty($uploads['basedir'])) {
            return $url;
        }

        // Determine the relative file path (e.g., /2025/06/image.png)
        $relative_path = str_replace($uploads['baseurl'], '', $url);
        $local_path = $uploads['basedir'] . $relative_path;

        if (file_exists($local_path)) {
            return $url; // file exists locally → no rewrite needed
        }

        $remote_base = get_option('lmcdn_remote_base_url', '');
        $secret_key = get_option('lmcdn_proxy_secret', '');

        if (empty($remote_base) || empty($secret_key)) {
            return $url; // bail if config missing
        }

        // Build rewritten proxy API URL with shared secret key
        $rewritten = trailingslashit($remote_base) . 'wp-json/lmcdn/v1/proxy?path=' . ltrim($relative_path, '/') . '&key=' . urlencode($secret_key);

        return $rewritten;
    }

    /**
     * Rewrites the main image src URL used in wp_get_attachment_image_src().
     *
     * @param array|false $image Image data array [0] => URL, or false.
     * @param int $attachment_id Attachment post ID.
     * @return array|false Modified image data array or false if invalid.
     */
    public function rewrite_image_src($image, int $attachment_id)
    {
        if (!is_array($image) || empty($image[0])) {
            return $image;
        }

        $image[0] = $this->rewrite_missing_media_url($image[0], $attachment_id);
        return $image;
    }

    /**
     * Rewrites each URL in the srcset attribute built by wp_calculate_image_srcset().
     *
     * @param array $sources Array of srcset sources.
     * @param array $size_array Requested image dimensions.
     * @param string $image_src Original image source URL.
     * @param array $image_meta Attachment metadata.
     * @param int $attachment_id Attachment post ID.
     * @return array Modified srcset sources array.
     */
    public function rewrite_srcset(array $sources, array $size_array, string $image_src, array $image_meta, int $attachment_id): array
    {
        foreach ($sources as $width => $source) {
            if (!empty($source['url'])) {
                $sources[$width]['url'] = $this->rewrite_missing_media_url($source['url'], $attachment_id);
            }
        }
        return $sources;
    }

    /**
     * Rewrites the main image URL used by wp_get_attachment_image_url().
     *
     * @param string $url The original image URL.
     * @param int $post_id Attachment post ID.
     * @return string The rewritten or original image URL.
     */
    public function rewrite_image_url(string $url, int $post_id): string
    {
        return $this->rewrite_missing_media_url($url, $post_id);
    }

    /**
     * Rewrites <img src="..."> URLs in post content if local files are missing.
     *
     * @param string $content The post content.
     * @return string The updated post content with rewritten image URLs.
     */
    public function rewrite_images_in_content(string $content): string
    {
        // Quick bail: no <img> tags found → nothing to do
        if (stripos($content, '<img') === false) {
            return $content;
        }

        // Use preg_replace_callback to find and update all <img> tags
        return preg_replace_callback(
            '#<img\s[^>]*src=["\']([^"\']+)["\'][^>]*>#i',
            function ($matches) {
                $original_tag = $matches[0];
                $src = $matches[1];

                $rewritten_src = $this->rewrite_missing_media_url($src, 0);

                // Only replace if the URL actually changed → avoids unnecessary replacements
                if ($rewritten_src !== $src) {
                    return str_replace($src, esc_url($rewritten_src), $original_tag);
                }

                return $original_tag;
            },
            $content
        );
    }
}
